trigger:
  branches:
    include:
      - main

pool:
 name: flask
 agent.name: flas

stages:
   - stage: "Test"
     jobs:
       - job: "Test"
         steps:
           - task: SonarQubePrepare@7
             inputs:
               SonarQube: 'sonarqube'
               scannerMode: 'cli'
               configMode: 'manual'
               cliProjectKey: 'flask-app'
               cliProjectName: 'flask'
               cliSources: '.'
           - task: SonarQubeAnalyze@7
             inputs:
               jdkversion: 'JAVA_HOME_17_X64'
           - task: SonarQubePublish@7
             inputs:
                pollingTimeoutSec: '300'
   - stage: "Build"
     jobs:
        - job: "Docker"
          steps:
            - task: Docker@2
              inputs:
                containerRegistry: 'registry container'
                repository: 'flask'
                command: 'buildAndPush'
                Dockerfile: './dockerfile'
                tags: 'latest'
            - task: CopyFiles@2
              inputs:
                Contents: 'aks-deployment'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
